# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chattingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChattingPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 808)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(338, 419))
        self.centralwidget.setStyleSheet("background-color:rgb(178,199,217);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.resultBrower = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultBrower.setMouseTracking(False)
        self.resultBrower.setStyleSheet("border:none;")
        self.resultBrower.setObjectName("resultBrower")
        self.gridLayout.addWidget(self.resultBrower, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.inputButton = QtWidgets.QPushButton(self.centralwidget)
        self.inputButton.setMinimumSize(QtCore.QSize(50, 20))
        self.inputButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.inputButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inputButton.setStyleSheet("background-color:rgb(255,236,66);\n"
                                       "border:1px solid rgb(239,225,95);\n"
                                       "border-radius:1px;\n"
                                       "color:rgb(198,185,60);\n"
                                       "font-size:12px\n"
                                       "")
        self.inputButton.setObjectName("inputButton")
        self.gridLayout_3.addWidget(self.inputButton, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("background-color:white;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_2.setStyleSheet("background-color:white;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        self.inputText = QtWidgets.QTextEdit(self.centralwidget)
        self.inputText.setMaximumSize(QtCore.QSize(16777215, 100))
        self.inputText.setMouseTracking(True)
        self.inputText.setStyleSheet("background-color:white;\n"
                                     "border:none;")
        self.inputText.setObjectName("inputText")
        self.gridLayout_3.addWidget(self.inputText, 1, 0, 3, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(15, 0))
        self.label_3.setMaximumSize(QtCore.QSize(0, 16777215))
        self.label_3.setStyleSheet("background-color:white;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 2, 3, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resultBrower.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                             "<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.inputButton.setText(_translate("MainWindow", "전송"))
